name: "winapps" # Docker Compose Project Name.
volumes:
  data:
services:
  windows:
    image: ghcr.io/dockur/windows:latest
    container_name: WinApps # Created Docker VM Name.
    environment:
      VERSION: "tiny11"
      RAM_SIZE: "10G" # RAM allocated to the Windows VM.
      CPU_CORES: "12" # CPU cores allocated to the Windows VM.
      DISK_SIZE: "64G" # Size of the primary hard disk.
      USERNAME: "Docker" # Edit here to set a custom Windows username. The default is 'MyWindowsUser'.
      PASSWORD: "novarch" # Edit here to set a password for the Windows user. The default is 'MyWindowsPassword'.
      HOME: "${HOME}" # Set path to Linux user home folder.
    # Rest of your config remains the same
    ports:
      - 8006:8006 
      - 3389:3389/tcp 
      - 3389:3389/udp 
    cap_add:
      - NET_ADMIN  # Add network permission
    stop_grace_period: 120s 
    restart: "no" 
    volumes:
      - data:/storage 
      - ${HOME}:/shared 
      - ./oem:/oem 
    devices:
      - /dev/kvm # Enable KVM.
      - /dev/net/tun # Enable tuntap
      # - /dev/nvidia0:/dev/nvidia0 # NVIDIA GPU device
      # - /dev/nvidiactl:/dev/nvidiactl # NVIDIA control interface
      # - /dev/nvidia-uvm:/dev/nvidia-uvm # NVIDIA Unified Memory
      # - /dev/nvidia-modeset:/dev/nvidia-modeset # NVIDIA mode setting
